[package]
name = "prest"
version = "0.3.10"
authors = [
	"Georgios Gerasimou <giorgosgerasimou@hotmail.com>",
	"Matus Tejiscak <ziman@functor.sk>"
]

[dependencies]
argparse = "*"
rand = "*"
base64 = "*"
byteorder = "*"
num = "*"
rayon = "*"
#nalgebra = "*"
#log = "*"

[lib]
path = "src/lib.rs"

# vim: ft=cfg
